---

- name: Test Playbook
  gather_facts: false
  hosts: localhost
  vars: 
    ExecuteRole: "Tapan"
    EnvPrefix: "EnvPrefix"
    CustomerPrefix: "CustomerPrefix"
    logGroup: "logGroup"
    ExtensionsBundleMetricFatalErrorPattern: "ExtensionsBundleMetricFatalErrorPattern"
    BatchDaemonDefinitions: ["RAM", "HARI"]
  tasks:

    - name: Test1
      set_fact:
        sourceDetail: 
          RoleName: "{{ ExecuteRole }}"


- name: Create IP address
  hosts: localhost
  gather_facts: false

  vars:
    ansible_python_interpreter: /usr/bin/python3
    service_account_file: auth.json
    project: happy-376214
    auth_kind: serviceaccount
    scopes:
      - https://www.googleapis.com/auth/compute

  tasks:
   - name: Allocate an IP Address
     gcp_compute_address:
         state: absent
         name: 'test-address1'
         region: 'us-west1'
         project: "{{ project }}"
         auth_kind: "{{ auth_kind }}"
         service_account_file: "{{ service_account_file }}"
         scopes: "{{ scopes }}"

    - name: Get backend services
      gcp_compute_backend_service_facts:
        project: "{{ project }}"
        auth_kind: "{{ auth_kind }}"
        service_account_file: "{{ service_account_file }}"
        scopes: "{{ scopes }}"
      register: backend_services

    - name: Print backend service names
      debug:
        msg: "{{ backend_services }}"
